import {
  getApplication,
  registerApplication,
} from "@/core/process/app-registry";
import type { ApplicationManifest } from "@/types/application";

export enum AppKey {
  Welcome = "welcome",
  Portfolio = "portfolio",
  AboutMe = "about-me",
  Projects = "projects",
  Skills = "skills",
  Contact = "contact",
  Resume = "resume",
  Photography = "photography",
  Gallery3D = "gallery-3d",
  Timeline = "timeline",
  Certificates = "certificates",
  Ideas = "ideas",
  Paint = "paint",
  Minesweeper = "minesweeper",
  Checkers = "checkers",
  Game2048 = "game-2048",
  TicTacToe = "tic-tac-toe",
  Shooter = "shooter",
  Agent = "agent",
  Achievements = "achievements",
  FileViewer = "file-viewer",
  RecycleBin = "recycle-bin",
}

export const APP_CATALOG: readonly ApplicationManifest[] = [
  {
    id: AppKey.Welcome,
    title: "Добро пожаловать в TamirlanOS",
    iconSrc: "/assets/icons/welcome.svg",
    defaultSize: { width: 430, height: 400 },
    minSize: { width: 360, height: 320 },
    resizable: true,
    singleton: true,
  },
  {
    id: AppKey.Portfolio,
    title: "Проводник портфолио",
    iconSrc: "/assets/icons/portfolio.svg",
    defaultSize: { width: 480, height: 380 },
    minSize: { width: 360, height: 280 },
    resizable: true,
    singleton: true,
  },
  {
    id: AppKey.AboutMe,
    title: "Обо мне",
    iconSrc: "/assets/icons/about-me.svg",
    defaultSize: { width: 780, height: 560 },
    minSize: { width: 520, height: 400 },
    resizable: true,
    singleton: true,
  },
  {
    id: AppKey.Projects,
    title: "Проекты",
    iconSrc: "/assets/icons/projects.svg",
    defaultSize: { width: 580, height: 420 },
    minSize: { width: 440, height: 320 },
    resizable: true,
    singleton: true,
  },
  {
    id: AppKey.Skills,
    title: "Навыки",
    iconSrc: "/assets/icons/skills.svg",
    defaultSize: { width: 580, height: 440 },
    minSize: { width: 340, height: 300 },
    resizable: true,
    singleton: true,
  },
  {
    id: AppKey.Contact,
    title: "Контакты",
    iconSrc: "/assets/icons/contact.svg",
    defaultSize: { width: 430, height: 330 },
    minSize: { width: 360, height: 280 },
    resizable: true,
    singleton: true,
  },
  {
    id: AppKey.Resume,
    title: "Резюме",
    iconSrc: "/assets/icons/resume.svg",
    defaultSize: { width: 530, height: 470 },
    minSize: { width: 420, height: 340 },
    resizable: true,
    singleton: true,
  },
  {
    id: AppKey.Photography,
    title: "Фотография",
    iconSrc: "/assets/icons/photography.svg",
    defaultSize: { width: 620, height: 460 },
    minSize: { width: 460, height: 340 },
    resizable: true,
    singleton: true,
  },
  {
    id: AppKey.Gallery3D,
    title: "3D-галерея",
    iconSrc: "/assets/icons/gallery-3d.svg",
    defaultSize: { width: 480, height: 430 },
    minSize: { width: 380, height: 340 },
    resizable: true,
    singleton: true,
  },
  {
    id: AppKey.Timeline,
    title: "Хронология",
    iconSrc: "/assets/icons/timeline.svg",
    defaultSize: { width: 470, height: 450 },
    minSize: { width: 380, height: 320 },
    resizable: true,
    singleton: true,
  },
  {
    id: AppKey.Certificates,
    title: "Сертификаты",
    iconSrc: "/assets/icons/certificates.svg",
    defaultSize: { width: 540, height: 450 },
    minSize: { width: 420, height: 340 },
    resizable: true,
    singleton: true,
  },
  {
    id: AppKey.Ideas,
    title: "Идеи",
    iconSrc: "/assets/icons/ideas.svg",
    defaultSize: { width: 470, height: 400 },
    minSize: { width: 360, height: 300 },
    resizable: true,
    singleton: true,
  },
  {
    id: AppKey.Paint,
    title: "Paint",
    iconSrc: "/assets/icons/paint.svg",
    defaultSize: { width: 640, height: 500 },
    minSize: { width: 420, height: 340 },
    resizable: true,
    singleton: true,
  },
  {
    id: AppKey.Minesweeper,
    title: "Сапёр",
    iconSrc: "/assets/icons/minesweeper.svg",
    defaultSize: { width: 340, height: 430 },
    minSize: { width: 300, height: 380 },
    resizable: true,
    singleton: true,
  },
  {
    id: AppKey.Checkers,
    title: "Шашки",
    iconSrc: "/assets/icons/checkers.svg",
    defaultSize: { width: 430, height: 500 },
    minSize: { width: 340, height: 420 },
    resizable: true,
    singleton: true,
  },
  {
    id: AppKey.Game2048,
    title: "2048",
    iconSrc: "/assets/icons/game-2048.svg",
    defaultSize: { width: 380, height: 470 },
    minSize: { width: 320, height: 420 },
    resizable: true,
    singleton: true,
  },
  {
    id: AppKey.TicTacToe,
    title: "Крестики-нолики",
    iconSrc: "/assets/icons/tic-tac-toe.svg",
    defaultSize: { width: 360, height: 400 },
    minSize: { width: 300, height: 360 },
    resizable: true,
    singleton: true,
  },
  {
    id: AppKey.Shooter,
    title: "Арена-шутер",
    iconSrc: "/assets/icons/shooter.svg",
    defaultSize: { width: 540, height: 480 },
    minSize: { width: 360, height: 380 },
    resizable: true,
    singleton: true,
  },
  {
    id: AppKey.Agent,
    title: "Агент 5.6",
    iconSrc: "/assets/icons/agent.svg",
    defaultSize: { width: 600, height: 520 },
    minSize: { width: 340, height: 400 },
    resizable: true,
    singleton: true,
    chrome: false,
  },
  {
    id: AppKey.Achievements,
    title: "Достижения",
    iconSrc: "/assets/icons/achievements.svg",
    defaultSize: { width: 440, height: 480 },
    minSize: { width: 320, height: 360 },
    resizable: true,
    singleton: true,
  },
  {
    id: AppKey.RecycleBin,
    title: "Корзина",
    iconSrc: "/assets/icons/recycle-bin.svg",
    defaultSize: { width: 620, height: 470 },
    minSize: { width: 320, height: 360 },
    resizable: true,
    singleton: true,
  },
  {
    id: AppKey.FileViewer,
    title: "Просмотр файла",
    iconSrc: "/assets/icons/file-viewer.svg",
    defaultSize: { width: 520, height: 430 },
    minSize: { width: 320, height: 300 },
    resizable: true,
    singleton: true,
    chrome: false,
  },
];

export function installApps(): void {
  for (const manifest of APP_CATALOG) {
    if (!getApplication(manifest.id)) registerApplication(manifest);
  }
}
